services:
  pineapple:
    image: nkwjg/pineapple-api:latest
    container_name: pineapple-api
    ports:
      - "8888:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGODB_URL: mongodb://root:password@mongodb:27017/pineapple?authSource=admin
      KAFKA_BOOTSTRAP_SERVER: pa-kafka:9092
      JWT_KEY: afousvoiaovdoias
      FRONTEND_ADDRESS: https://www.manthe.top

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pineapple
    volumes:
      - ./docker/mongo:/data/db

  redis:
    image: redis:latest
    container_name: pa_redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: pa-zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    container_name: pa-kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"