

spring:
  application:
    name: pineapple-api
  security:
    jwt:
      key: ${JWT_KEY}
      expire: 1
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: pineapple-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.BytesDeserializer
  data:
    mongodb:
      uri: ${MONGODB_URL}

pineapple:
  frontend:
    # 真正部署的地址, localhost上的vite是永远被允许的
    address: ${FRONTEND_ADDRESS}
  account:
    # please modify the password to keep your server safe
    username: pineapple
    password: password
server:
  port: 8080